import type { Metadata } from "next";
import localFont from "next/font/local";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const work = localFont({
  src: "./fonts/WorkSans.ttf",
  variable: "--font-work",
  weight: "100 200 300 400 500 600 700 800 900",
});
const open = localFont({
  src: "./fonts/open.ttf",
  variable: "--font-open",
  weight: "100 200 300 400 500 600 700 800 900",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${work.variable} ${open.variable} ${dmSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
